CM-138: User Groups Management implementation (#1)
* CM-139: base project configuration, eslint, main route

* CM-139: basic structure of tasks view

* CM-139: basic view of task traiage

* CM-139: basic view of task triage

* CM-139: task preview improvements

* CM-139: import fix

* CM-138: user groups management page and basic searcher

* CM-138: reducer, actions, fetchTaskGroups, searcher

* CM-138: taskExecutorsPicker, taskGroupPage, taskGroupHeadPanel

* CM-138: fetch task group, clear on unmount

* OTC-138: remove package-lock json

* CM-138: implementation of create/update mutation, executors picker fix

* CM-138: removal of console log

* CM-138: filtering, sorting, searching improvements, executorsPicker fixes

* CM-138: create PERFORM_MUTATION and adjust existing logic, constants fix

* CM-138: name of function changed

* CM-138: TaskExecutorsPicker fixes

* CM-138: component name changed - TaskDetailsPage

diff --git a/.github/workflows/CI_and_build.yml b/.github/workflows/CI_and_build.yml
--- a/.github/workflows/CI_and_build.yml
+++ b/.github/workflows/CI_and_build.yml
@@ -30,15 +30,15 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
-      # Runs a single command using the runners shell
-      - name: get dependences
-        run: |
-          node openimis-config.js openimis.json
       - name: Install dependencies
         run : yarn install 
       - name: build
         run : yarn build 
-      - uses: actions/upload-artifact@v2
-        with:
-          name: frontend-node${{ matrix.node-version }}-${{github.run_number}}-${{github.sha}}
-          path: ./build/*
+      - name: Check build status
+        run: |
+          if [ -d "dist" ]; then
+            echo "Build successful!"
+          else
+            echo "Build failed!"
+            exit 1
+          fi
